give  Tue 14 Jul 17:29:01 AEST 2020: All test scripts now written - just need to add some more flavourful cases throughout, and test merge a liiiiitle bit more.

diff --git a/shrug-branch b/shrug-branch
--- a/shrug-branch
+++ b/shrug-branch
@@ -1,33 +1,55 @@
 #!/bin/dash
 
+if ! test -d ".shrug"; then
+    >&2 echo "shrug-branch: error: no .shrug directory containing shrug repository exists"
+    exit 1
+fi 
+
 branch=`cat ".shrug/branch.txt" | head -1`
 commits=`cat ".shrug/branch.txt" | tail -1`
 
 if test $commits -eq 0; then
-    echo "shrug-branch: error: your repository does not have any commits yet"
-    exit
+    >&2 echo "shrug-branch: error: your repository does not have any commits yet"
+    exit 1
 fi
 
+if test $# -eq 1 && test "$1" = "-d"; then
+    >&2 echo "shrug-branch: error: branch name required"
+    exit 1
+fi
+
+if test $# -ge 2; then
+    if test $# -eq 2; then
+        if test "$1" != "-d"; then
+            >&2 echo "usage: shrug-branch [-d] <branch>"
+            exit 1
+        fi
+    else
+        >&2 echo "usage: shrug-branch [-d] <branch>"
+        exit 1
+    fi
+    
+fi
 if test "$1" = "-d"; then
-    test "$2" = "master" && echo "shrug-branch: error: can not delete branch '$2'" && exit
-    test "$2" = "$branch" && echo "shrug-branch: error: you are currently in this branch. Move to another to delete it." && exit
-    ! test -d ".shrug/.$2" && echo "shrug-branch: error: branch '$2' does not exist" && exit
+    test "$2" = "master" && >&2 echo "shrug-branch: error: can not delete branch '$2'" && exit 1
+    test "$2" = "$branch" && >&2 echo "shrug-branch: error: you are currently in this branch. Move to another to delete it." && exit 1
+    ! test -d ".shrug/.$2" && >&2 echo "shrug-branch: error: branch '$2' does not exist" && exit 1
 
     for file in .shrug/.$2/.files/*
     do
         filename=`basename $file`
         if test -f "$filename"; then
             difference=`diff "$filename" "$file" | wc -l`
-            test $difference -gt 0 && echo "shrug-branch: error: branch '$2' has unmerged changes" && exit
+            test $difference -gt 0 && >&2 echo "shrug-branch: error: branch '$2' has unmerged changes" && exit 1
         else
-            # echo "$filename not here" && ls
-            echo "shrug-branch: error: branch '$2' has unmerged changes" && exit
+            >&2 echo "shrug-branch: error: branch '$2' has unmerged changes"
+            exit 1
         fi
     done
 
-    test -d ".shrug/.$2" && rm -r ".shrug/.$2" && echo "Deleted branch '$2'"
+    rm -r ".shrug/.$2" && echo "Deleted branch '$2'"
 elif test "$#" = "1"; then
-    test -d ".shrug/.$1" && echo "shrug-branch: error: branch '$1' already exists" && exit
+    test -d ".shrug/.$1" && >&2 echo "shrug-branch: error: branch '$1' already exists" && exit 1
 
     existing_files=`ls | tr ' ' '\n' | egrep -v "shrug-*" | egrep -v "diary.txt"`
     ! test -d ".shrug/.$branch/.files" && mkdir ".shrug/.$branch/.files"
diff --git a/shrug-checkout b/shrug-checkout
--- a/shrug-checkout
+++ b/shrug-checkout
@@ -1,11 +1,33 @@
 #!/bin/dash
 
+if ! test -d ".shrug"; then
+    >&2 echo "shrug-checkout: error: no .shrug directory containing shrug repository exists"
+    exit 1
+fi 
+
+if test $# -eq 1 && test "$1" = "-d"; then
+    >&2 echo "shrug-checkout: error: branch name required"
+    exit 1
+fi
+
 branch=`cat ".shrug/branch.txt" | head -1`
+commits=`cat ".shrug/branch.txt" | tail -1`
+
+if test $commits -eq 0; then
+    >&2 echo "shrug-checkout: error: your repository does not have any commits yet"
+    exit 1
+fi
+
+if test $# -gt 1; then
+    >&2 echo "usage: shrug-checkout <branch>"
+    exit 1
+fi
 
 if test "$1" = "$branch"; then
     echo "Already on '$branch'"
 elif ! test -d ".shrug/.$1"; then
-    echo "shrug-checkout: error: unknown branch '$1'"
+    >&2 echo "shrug-checkout: error: unknown branch '$1'"
+    exit 1
 else
     existing_files=`ls | tr ' ' '\n' | egrep -v "shrug-*" | egrep -v "diary.txt"`
     for f in $existing_files
@@ -45,11 +67,11 @@ else
                     fi
                 # fi
                     test "$error" = "true" && # echo "the error files are as follows: '$errorfiles'" &&
-                    echo "shrug-checkout: error: Your changes to the following files would be overwritten by checkout:" &&
+                    >&2 echo "shrug-checkout: error: Your changes to the following files would be overwritten by checkout:" &&
                     for nomerge in $errorfiles
                     do
                         echo "$nomerge"
-                    done && exit
+                    done && exit 1
                     test "$error" = "false" && cp "$f" ".shrug/.$1/.files"
                 fi
             fi
@@ -76,11 +98,11 @@ else
                     errorfiles="$errorfiles$f "
                 fi
                 test "$error" = "true" && # echo "the error files are as follows: '$errorfiles'" &&
-                echo "shrug-checkout: error: Your changes to the following files would be overwritten by checkout:" &&
+                >&2 echo "shrug-checkout: error: Your changes to the following files would be overwritten by checkout:" &&
                 for nomerge in $errorfiles
                 do
                     echo "$nomerge"
-                done && exit
+                done && exit 1
                 test "$error" = "false" && cp "$f" ".shrug/.$1/.files"
             # else
 
diff --git a/shrug-merge b/shrug-merge
--- a/shrug-merge
+++ b/shrug-merge
@@ -1,22 +1,41 @@
 #!/bin/dash
 
+if ! test -d ".shrug"; then
+    >&2 echo "shrug-merge: error: no .shrug directory containing shrug repository exists"
+    exit 1
+fi
+
 branch=`cat ".shrug/branch.txt" | head -1`
 log_master=".shrug/.$branch/.log/log.txt"
 commits=`wc -l $log_master | sed 's/ /,/' | cut -d, -f1`
 
 if test $commits -eq 0; then
-    echo "shrug-merge: error: your repository does not have any commits yet"
-    exit
+    >&2 echo "shrug-merge: error: your repository does not have any commits yet"
+    exit 1
 fi
 
-if test "$2" != "-m" || test "$3" = ""; then
-    echo "shrug-merge: error: empty commit message"
-    exit
+if test $# -ge 0; then
+    test $# -eq 0 &&
+    >&2 echo "usage: shrug-merge <branch|commit> -m message" &&
+    exit 1
+    
+    test $# -gt 1 && test "$2" != "-m" &&
+    >&2 echo "usage: shrug-merge <branch|commit> -m message" &&
+    exit 1
+
+    test $# -eq 2 &&
+    >&2 echo "usage: shrug-merge <branch|commit> -m message" &&
+    exit 1
+fi
+
+if  test $# -eq 1 || test "$3" = ""; then
+    >&2 echo "shrug-merge: error: empty commit message"
+    exit 1
 fi
 
 if ! test -d ".shrug/.$1"; then
-    echo "shrug-merge: error: unknown branch '$1'"
-    exit
+    >&2 echo "shrug-merge: error: unknown branch '$1'"
+    exit 1
 else
     error="false"
     errorfiles=""
@@ -76,7 +95,7 @@ else
                         break
                     fi
                 done
-                test $merged -gt 0 && echo "Already up to date" && exit
+                test $merged -gt 0 && >&2 echo "Already up to date" && exit 0
                 
                 # echo "diff output for diff between latest common commit and merging branch:"
                 # diff "$latest_common_commit" ".shrug/.$1/.log/$latest_branch_version-$filename"
@@ -176,11 +195,11 @@ else
 
 
     test "$error" = "true" && 
-    echo "shrug-merge: error: These files can not be merged:" && 
+    >&2 echo "shrug-merge: error: These files can not be merged:" && 
     for nomerge in $errorfiles
     do
         echo "$nomerge"
-    done
+    done && exit 1
 
     if test "$error" = "false" && test "$copyall" = "true"; then
         ## to check if we fast forward, or are already up to date, we diff the currdir file 
@@ -209,7 +228,8 @@ else
                 index_and_repo=`diff "$filename" ".shrug/.$branch/$filename" | wc -l`
 
                 if test $index_and_curr -gt 0 || test $index_and_repo -gt 0; then
-                    echo "shrug-merge: error: can not merge: local changes to files"
+                    >&2 echo "shrug-merge: error: can not merge: local changes to files"
+                    exit 1
                 else
                     cp "$file" ./
                     cp "$file" ".shrug/.$branch/"
@@ -224,9 +244,9 @@ else
             fi
         done
         # echo "fast_forward: $fast_forward, difference: $difference"
-        test "$fast_forward" = "false" && echo "Already up to date"
+        test "$fast_forward" = "false" && echo "Already up to date" && exit 0
         test "$fast_forward" = "true" && echo "Fast-forward: no commit created" &&
-        cat ".shrug/.$1/.log/log.txt" >> ".shrug/.$branch/.log/log.txt"
+        cat ".shrug/.$1/.log/log.txt" >> ".shrug/.$branch/.log/log.txt" && exit 0
     fi
 
     committed=0
@@ -274,7 +294,7 @@ else
             
             ## Firstly before we get started in merging stuff, let's check if we are already up to date.
             curr_and_branch=`diff "$filename" ".shrug/.$1/.log/$latest_branch_version-$filename" | wc -l`            
-            test $curr_and_branch -eq 0 && echo "Already up to date" && exit
+            test $curr_and_branch -eq 0 && echo "Already up to date" && exit 0
 
             ## Secondly, let's make sure that we don't have any local changes:
             index_and_curr=0
@@ -287,7 +307,8 @@ else
             index_and_repo=`diff "$filename" ".shrug/.$branch/$filename" | wc -l`
 
             if test $index_and_curr -gt 0 || test $index_and_repo -gt 0; then
-                echo "shrug-merge: error: can not merge: local changes to files"
+                >&2 echo "shrug-merge: error: can not merge: local changes to files"
+                exit 1
             fi
 
             ## To do the merging, we want to compare our file from the branch getting merged into our current branch, and the file
