give  Tue 14 Jul 15:41:46 AEST 2020: just pushing up before i accidentally delete stuff from my test scripts lol

diff --git a/shrug-log b/shrug-log
--- a/shrug-log
+++ b/shrug-log
@@ -2,7 +2,19 @@
 
 if ! test -d ".shrug"; then
     >&2 echo "shrug-log: error: no .shrug directory containing shrug repository exists"
-    exit
+    exit 1
+fi
+
+commits=`cat ".shrug/branch.txt" | tail -1`
+
+if test $commits -eq 0; then
+    >&2 echo "shrug-log: error: your repository does not have any commits yet"
+    exit 1
+fi
+
+if test $# -gt 0; then
+    >&2 echo "usage: shrug-log"
+    exit 1
 fi
 
 branch=`cat ".shrug/branch.txt" | head -1`
diff --git a/shrug-rm b/shrug-rm
--- a/shrug-rm
+++ b/shrug-rm
@@ -1,15 +1,25 @@
 #!/bin/dash
 
+if ! test -d ".shrug"; then
+    >&2 echo "shrug-rm: error: no .shrug directory containing shrug repository exists"
+    exit 1
+fi
+
 branch=`cat ".shrug/branch.txt" | head -1`
 index=".shrug/.$branch/.index"
 log=".shrug/.$branch/.log/log.txt"
 force=0
 cached=0
-commits=`wc -l $log | sed 's/ /,/' | cut -d, -f1`
+commits=`cat ".shrug/branch.txt" | tail -1`
 
 if test $commits -eq 0; then
-    echo "shrug-rm: error: your repository does not have any commits yet"
-    exit
+    >&2 echo "shrug-rm: error: your repository does not have any commits yet"
+    exit 1
+fi
+
+if test $# -eq 0; then
+    >&2 echo "usage: shrug-rm [--force] [--cached] <filenames>"
+    exit 1
 fi
 
 if test "$1" = "--force"; then
@@ -23,15 +33,15 @@ files=`echo $@ | sed 's/--cached//' | sed 's/--force//'`
 
 for f in $files
 do
-    ! test -f "$index/$f" && echo "shrug-rm: error: '$f' is not in the shrug repository" && exit
+    ! test -f "$index/$f" && >&2 echo "shrug-rm: error: '$f' is not in the shrug repository" && exit 1
 done
 
 if test $force -eq 1; then
     for f in $files
     do
         if ! test -f ".shrug/.$branch/.index/$f"; then
-            echo "shrug-rm: error: '$f' is not in the shrug repository"
-            exit
+            >&2 echo "shrug-rm: error: '$f' is not in the shrug repository"
+            exit 1
         else
             if test "$2" = "--cached"; then
                 rm ".shrug/.$branch/.index/$f"
@@ -46,10 +56,13 @@ else
     do
         if ! test -f ".shrug/.$branch/$file"; then
             if ! test -f "$index/$file"; then
-                echo "shrug-rm: error: '$file' is not in the shrug repository"
-                exit
+                >&2 echo "shrug-rm: error: '$file' is not in the shrug repository"
+                exit 1
             else
-                ! test $cached -eq 1 && echo "shrug-rm: error: '$file' has changes staged in the index"
+                if ! test $cached -eq 1; then
+                    >&2 echo "shrug-rm: error: '$file' has changes staged in the index"
+                    exit 1
+                fi
                 test $cached -eq 1 && rm "$index/$file" && echo "$file - unstaged" >> ".shrug/.$branch/.log/bin.txt"
             fi
         else
@@ -58,7 +71,8 @@ else
             compare_index_dir=`diff "$index/$filename" "$file" | wc -l`
 
             if test $compare_repo_index -gt 0 && test $compare_index_dir -gt 0; then
-                echo "shrug-rm: error: '$file' in index is different to both working file and repository"
+                >&2 echo "shrug-rm: error: '$file' in index is different to both working file and repository"
+                exit 1
             elif test $cached -eq 1; then
                 rm "$index/$file"
                 echo "$file - unstaged" >> ".shrug/.$branch/.log/bin.txt"
@@ -69,13 +83,14 @@ else
             else
                 test $compare_repo_index -eq 0 &&
                 test $compare_index_dir -gt 0 &&
-                echo "shrug-rm: error: '$file' in repository is different to working file"
+                >&2 echo "shrug-rm: error: '$file' in repository is different to working file" &&
+                exit 1
 
                 test $compare_repo_index -gt 0 &&
                 test $compare_index_dir -eq 0 &&
-                echo "shrug-rm: error: '$file' has changes staged in the index"
+                >&2 echo "shrug-rm: error: '$file' has changes staged in the index" &&
+                exit 1
             fi
         fi
-
     done
 fi
diff --git a/shrug-show b/shrug-show
--- a/shrug-show
+++ b/shrug-show
@@ -1,5 +1,23 @@
 #!/bin/dash
 
+if ! test -d ".shrug"; then
+    >&2 echo "shrug-show: error: no .shrug directory containing shrug repository exists"
+    exit 1
+fi
+
+if test $# -eq 0 || test $# -gt 1; then
+    >&2 echo "usage: shrug-show <commit>:<filename>"
+    exit 1
+fi
+
+if test $# -eq 1; then
+    check=`echo "$1" | egrep ':' | wc -l`
+    if test $check -eq 0; then
+        >&2 echo "shrug-show: error: invalid object $1"
+        exit 1
+    fi
+fi
+
 branch=`cat ".shrug/branch.txt" | head -1`
 logfiles=".shrug/.$branch/.log"
 indexfiles=".shrug/.$branch/.index"
@@ -17,13 +35,16 @@ else
     if ! test "$ncommit" = ""; then
         count=`ls "$logfiles/" | egrep "$ncommit-*" | wc -l | sed 's/ /,/' | cut -d, -f1`
         if test $count -eq 0; then
-            echo "shrug-show: error: unknown commit '$ncommit'"
+            >&2 echo "shrug-show: error: unknown commit '$ncommit'"
+            exit 1
         else
-            echo "shrug-show: error: '$filename' not found in commit $ncommit"
+            >&2 echo "shrug-show: error: '$filename' not found in commit $ncommit"
+            exit 1
         fi
     else
         if ! test -f "$indexfiles/$filename"; then
-            echo "shrug-show: error: '$filename' not found in index"
+            >&2 echo "shrug-show: error: '$filename' not found in index"
+            exit 1
         else
             cat "$indexfiles/$filename"
         fi
diff --git a/shrug-status b/shrug-status
--- a/shrug-status
+++ b/shrug-status
@@ -1,16 +1,26 @@
 #!/bin/dash
 
+if ! test -d ".shrug"; then
+    >&2 echo "shrug-status: error: no .shrug directory containing shrug repository exists"
+    exit 1
+fi
+
 branch=`cat ".shrug/branch.txt" | head -1`
 index=".shrug/.$branch/.index"
 log=".shrug/.$branch/.log/log.txt"
 repo=".shrug/.$branch/*"
-
-commits=`wc -l $log | sed 's/ /,/' | cut -d, -f1`
+commits=`cat ".shrug/branch.txt" | tail -1`
 
 if test $commits -eq 0; then
-    echo "shrug-status: error: your repository does not have any commits yet"
-    exit
+    >&2 echo "shrug-status: error: your repository does not have any commits yet"
+    exit 1
 fi
+
+if test $# -gt 0; then
+    >&2 echo "usage: shrug-status"
+    exit 1
+fi
+
 
 printf "" > ".shrug/.$branch/.log/status.txt"
 
