give  Mon 13 Jul 17:52:53 AEST 2020: Testing scripts updated

diff --git a/shrug-add b/shrug-add
--- a/shrug-add
+++ b/shrug-add
@@ -2,21 +2,28 @@
 
 repo=".shrug"
 
+if ! test -d ".shrug/"; then
+    >&2 echo "shrug-add: error: no .shrug directory containing shrug repository exists"
+    exit
+fi
+
+if test $# -eq 0; then
+    >&2 echo "usage: shrug-add <filenames>"
+    exit
+fi
+
 for var in "$@"
 do
     if test -f "$var"; then
-        if test -d ".shrug/"; then
-            branch=`cat ".shrug/branch.txt" | head -1`
-            cp "$var" ".shrug/.$branch/.index/"
-        else
-            echo "shrug-add: error: no .shrug directory containing shrug repository exists"
-        fi
+        branch=`cat ".shrug/branch.txt" | head -1`
+        cp "$var" ".shrug/.$branch/.index/"
     else
         branch=`cat ".shrug/branch.txt" | head -1`
         if test -f "$repo/.$branch/$var"; then
             echo "$var - deleted" > ".shrug/.$branch/.log/bin.txt" && rm "$repo/.$branch/$var"
         else
-            echo "shrug-add: error: can not open '$var'"
+            >&2 echo "shrug-add: error: can not open '$var'"
+            exit
         fi
     fi
 done
diff --git a/shrug-commit b/shrug-commit
--- a/shrug-commit
+++ b/shrug-commit
@@ -1,10 +1,21 @@
 #!/bin/dash
 
-if test $# -lt 2;
-then
-    echo "shrug-commit: Usage: shrug-commit [-a] -m commit-message"
+if ! test -d ".shrug"; then
+    >&2 echo "shrug-commit: error: no .shrug directory containing shrug repository exists"
     exit
 fi
+
+if test $# -lt 2 || test $# -gt 3;
+then
+    >&2 echo "usage: shrug-commit [-a] -m commit-message"
+    exit
+fi
+
+if test $# -eq 2 && test "$1" != "-a" && test "$1" != "-m";
+then
+    >&2 echo "usage: shrug-commit [-a] -m commit-message"
+    exit
+fi 
 
 branch=`cat ".shrug/branch.txt" | head -1`
 # cat ".shrug/branch.txt"
@@ -31,17 +42,7 @@ fi
 
 if test $1 = "-m" || test $2 = "-m";
 then
-    # echo $2
-    # ncommit=`wc -l $log | sed 's/ /,/' | cut -d, -f1`
     ncommit=`cat ".shrug/branch.txt" | tail -1`
-    # echo "ncommit $ncommit"
-    # echo commits=$ncommit
-    # if test $ncommit -gt 0; then
-    #     ncommit=`cat ".shrug/.$branch/.log/log.txt" | cut -d ' ' -f1 | tail -1`
-    #     ncommit=$(($ncommit + 1))
-    # fi
-    # echo "ncommit $ncommit"
-    # echo commits=$ncommit
     committed=0
     changes=0
     for FILE in $FILES
diff --git a/shrug-log b/shrug-log
--- a/shrug-log
+++ b/shrug-log
@@ -1,4 +1,9 @@
 #!/bin/dash
 
+if ! test -d ".shrug"; then
+    >&2 echo "shrug-log: error: no .shrug directory containing shrug repository exists"
+    exit
+fi
+
 branch=`cat ".shrug/branch.txt" | head -1`
 cat ".shrug/.$branch/.log/log.txt" | sort -r | egrep -v "^$" | uniq
